inherit_from:
  - .rubocop_todo.yml
  - .rubocop_airbnb.yml

#以下にはrubocopで検証したくないフォルダを指定する
AllCops:
  Exclude:
    - "db/**/*"
    - "bin/*"
    - "config/environments/*"
    - "config/application.rb"
    - "config/initializers/*"
    - "config/spring.rb"
    - "lib/tasks/*"
    - "vendor/**/*"
    - "path/ruby"
    - "Rakefile"
    - "Gemfile"

Metrics/AbcSize:
  Max: 24

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

RSpec/NotToNot:
  Enabled: false

Airbnb/OptArgParameters:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: leading

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: aligned