inherit_from:
  - .rubocop_todo.yml
  - .rubocop_airbnb.yml

#以下にはrubocopで検証したくないフォルダを指定する
AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - 'spec/**/*'
    - "db/**/*"
    - "bin/*"
    - "config/environments/*"
    - "config/application.rb"
    - "config/initializers/*"
    - "config/spring.rb"
    - "lib/tasks/*"
    - "vendor/**/*"
    - "path/ruby"
    - "Rakefile"
    - "Gemfile"

Metrics/AbcSize:
  Max: 24

Metrics/LineLength:
  Max: 160
  Exclude:
    - "db/migrate/*.rb"

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

RSpec/NotToNot:
  Enabled: false

Airbnb/OptArgParameters:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: leading

# and returnを許可
Style/AndOr:
  EnforcedStyle: conditionals

Style/BlockDelimiters:
  Enabled: false

# Layout/MultilineMethodCallIndentation:
#   EnforcedStyle: aligned