development:
  adapter: redis
  url: <%= ENV['REDIS_CONNECTION_STRING'] %>
  channel_prefix: <%= ENV['REDIS_CHANNEL_PREFIX'] %>
  # adapter: async

test:
  adapter: redis
  url: <%= ENV['REDIS_CONNECTION_STRING'] %>
  channel_prefix: <%= ENV['REDIS_CHANNEL_PREFIX'] %>
  # adapter: async

production:
  adapter: redis
  url: <%= ENV['REDIS_CONNECTION_STRING'] %>
  channel_prefix: <%= ENV['REDIS_CHANNEL_PREFIX'] %>
